const list = [
  { id: 1, dep: "Architecture & Planning" },
  { id: 2, dep: "Biosciences and Bioengineering" },
  { id: 3, dep: "Chemical Engineering" },
  { id: 4, dep: "Chemistry" },
  { id: 5, dep: "Civil Engineering" },
  { id: 6, dep: "Computer Science and Engineering" },
  { id: 7, dep: "Design" },
  { id: 8, dep: "Earthquake Engineering" },
  { id: 9, dep: "Earth Sciences" },
  { id: 10, dep: "Electrical Engineering" },
  { id: 11, dep: "Electronics and communication engineering" },
  { id: 12, dep: "Humanities and Social sciences" },
  { id: 13, dep: "Hydrology" },
  { id: 14, dep: "Hydro and Renewable energy" },
  { id: 15, dep: "Management studies" },
  { id: 16, dep: "Mathematics" },
  { id: 17, dep: "Mechanics and Industrial Engineering" },
  { id: 18, dep: "Metallurgical and Materials Engineering" },
  { id: 19, dep: "Paper Technology" },
  { id: 20, dep: "Physics" },
  { id: 21, dep: "WaterResource Department and Management" },
];

module.exports = list;